apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-cassandra-connector
  name: kafka-cassandra-connector
  namespace: kafka-cassandra-connector
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-cassandra-connector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-cassandra-connector
    spec:
      containers:
      - image: tbaums/kafka-cassandra-connector:latest
        imagePullPolicy: Always
        name: kafka-cassandra-connector
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          #TODO: get TLS working because this is v dangerous
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: KAFKA_ENDPOINT
          value: 'kafka-kafka-0.kafka-svc.platform-services.svc.cluster.local:9093'
        - name: CASSANDRA_ENDPOINT
          value: 'cassandra-node-0.cassandra-svc.platform-services.svc.cluster.local:9042'
      initContainers:
      - image: tbaums/cassandra-init:latest
        imagePullPolicy: Always
        name: cassandra-init
        env:
        - name: CASSANDRA_ENDPOINT
          value: 'cassandra-node-0.cassandra-svc.platform-services.svc.cluster.local'
        - name: CASSANDRA_PORT
          value: '9042'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
      

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cassandra-connector-svc
  namespace: kafka-cassandra-connector
spec:
  selector:
    app: kafka-cassandra-connector
  ports:
    - port: 3002
      targetPort: 3002
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: kafka-cassandra-connector-ingress
  namespace: kafka-cassandra-connector
spec:
  rules:
  - http:
      paths:
      - path: /kafka-cassandra-connector
        backend:
          serviceName: kafka-cassandra-connector-svc
          servicePort: 3002

# For local development or other purposes
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: svelte-client-np
# spec:
#   type: NodePort
#   selector:
#     app: svelte-client
#   ports:
#     # Which port on the node is the service available through?    
#     - nodePort: 30303
#     # Inside the cluster, what port does the service expose?
#       port: 3000
#     # Which port do pods selected by this service expose?
#       targetPort: 3000

